// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnyDy6M3esjHOq3665U8Rthdi58YWfNAs',
    appId: '1:750145129208:web:00e022574ef67c4e49090d',
    messagingSenderId: '750145129208',
    projectId: 'chem-buddy-10bfa',
    authDomain: 'chem-buddy-10bfa.firebaseapp.com',
    databaseURL: 'https://chem-buddy-10bfa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chem-buddy-10bfa.appspot.com',
    measurementId: 'G-HPL4XHQH56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXJiUertHOu318n32b-wYS6Wf_KOIJK4',
    appId: '1:750145129208:android:eab56eb1af0c784149090d',
    messagingSenderId: '750145129208',
    projectId: 'chem-buddy-10bfa',
    databaseURL: 'https://chem-buddy-10bfa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chem-buddy-10bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzV2vyKNtKC0dpmKu9rKiBMsgry9X524',
    appId: '1:750145129208:ios:f236c301a82de73d49090d',
    messagingSenderId: '750145129208',
    projectId: 'chem-buddy-10bfa',
    databaseURL: 'https://chem-buddy-10bfa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chem-buddy-10bfa.appspot.com',
    iosBundleId: 'com.example.chemBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzV2vyKNtKC0dpmKu9rKiBMsgry9X524',
    appId: '1:750145129208:ios:f236c301a82de73d49090d',
    messagingSenderId: '750145129208',
    projectId: 'chem-buddy-10bfa',
    databaseURL: 'https://chem-buddy-10bfa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chem-buddy-10bfa.appspot.com',
    iosBundleId: 'com.example.chemBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnyDy6M3esjHOq3665U8Rthdi58YWfNAs',
    appId: '1:750145129208:web:605953e895ed870849090d',
    messagingSenderId: '750145129208',
    projectId: 'chem-buddy-10bfa',
    authDomain: 'chem-buddy-10bfa.firebaseapp.com',
    databaseURL: 'https://chem-buddy-10bfa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chem-buddy-10bfa.appspot.com',
    measurementId: 'G-NM1RKQT18Y',
  );
}
